name: build-and-test
on: [push, pull_request]
jobs:
 run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Setup V
        uses: nocturlab/setup-vlang-action@v1
        with:
          v-version: master
        id: v
      
      - name: Setup Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 4

      - name: Build
        run: v -shared .
      - name: Test
        run: v test .